DROP INDEX [UK_PeopleAlias_PeopleID_Alias] ON [dbo].[PeopleAlias];

ALTER TABLE [PeopleAlias] ALTER COLUMN [alias] NVARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL;

CREATE UNIQUE NONCLUSTERED INDEX [UK_PeopleAlias_PeopleID_Alias] ON [dbo].[PeopleAlias] ([peopleId] ASC,	[alias] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
