export enum Place {
  Online = 1,
  Television = 2,
  Downloaded = 3,
  MovieTheater = 4,
  VideoClub = 5,
  Netflix = 6,
  AppleTv = 7,
  DisneyPlus = 8,
  PrimeVideo = 9,
  HBO = 10,
  Filmin = 11,
  HBOMax = 12,
  MovistarPlus = 13,
}
